### program 추가
POST http://localhost:8080/programs
Content-Type: application/json

{
  "number": 1,
  "name": "test",
  "theme": "test",
  "address": "address1 address2, address3",
  "introduction": "introduction test",
  "detailIntroduction": "hello \n test"
}

### prgram 들 조회
GET http://localhost:8080/programs

### prgram 조회
GET http://localhost:8080/programs/107

### program 수정
PUT http://localhost:8080/programs
Content-Type: application/json

{
  "id": 1,
  "number": 1,
  "name": "test-rename",
  "theme": "test",
  "address": "test",
  "introduction": "introduction test",
  "detailIntroduction": "hello \n test"
}

### h2 확인
GET http://localhost:8080/h2-console

### region 으로 조회
GET http://localhost:8080/search/summary
Content-Type: application/json

{
  "region": "평창군"
}

### region 으로 조회
GET http://localhost:8080/search/summary
Content-Type: application/json

{
  "region": "강원도"
}

### keyword 로 region 조회
GET http://localhost:8080/search/counting/region
Content-Type: application/json

{
  "keyword": "세계문화유산"
}

### keyword 로 region 조회
GET http://localhost:8080/search/counting/region
Content-Type: application/json

{
  "keyword": "남해"
}

### keyword 로 program 조회
GET http://localhost:8080/search/counting/program
Content-Type: application/json

{
  "keyword": "문화"
}

### keyword +region 으로 program 조회
GET http://localhost:8080/search/program
Content-Type: application/json

{
  "region": "평창",
  "keyword": "국립공원"
}

### keyword +region 으로 program 조회 2
GET http://localhost:8080/search/program
Content-Type: application/json

{
  "region": "남해",
  "keyword": "생태체험"
}

###
